### PR TITLE
feat: make vscode extension packageable by vsce

### PR DESCRIPTION
**Pull request by mcecode**
Related: #116

### CODE REVIEW

**Comment by elijah-potter** [comment]
This mostly looks good to me. My only concern is that you've added a new license file to the repo. Would it be possible to use the existing one?

**Comment by mcecode** [comment]
> My only concern is that you've added a new license file to the repo. Would it be possible to use the existing one?

I did worry about this too, but `vsce` doesn't have a flag for setting the path to a license file so I ended up adding one. I've pushed some changes to circumvent this. I used `just` to package the extension, adding a step of copying the license file at the root of the repo to `packages/vscode-plugin` before running `yarn package-extension`, which is just `vsce package`.

Since you previously mentioned hooking `vsce` into the CI, I thought an upside of using `just` is that it'd now be easier to setup an action that can deploy the extension to the Visual Studio Marketplace, as well as to the Open VSX Registry for editors that support the VS Code Extension protocol like VSCodium and Theia to be able to install and use it too.

Here's a possible `deploy_vscode_plugin.yml` workflow I drafted up for doing just that. Everytime a release tag get pushed, say `harper-vscode@0.0.1`, the action deploys the extension using the [Publish VS Code Extension GitHub Action](https://github.com/HaaLeo/publish-vscode-extension):

```yaml
name: Deploy VS Code Plugin

on:
  push:
    tags: [ 'harper-vscode*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Package Extension
        id: package-extension
        uses: extractions/setup-just@v2
        run: |
          just package-vscode
          echo "file=packages/vscode-plugin/harper-$(jq -r .version packages/vscode-plugin/package.json).vsix" >> "$GITHUB_OUTPUT"
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          registryUrl: https://marketplace.visualstudio.com
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ steps.package-extension.outputs.file }}
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.package-extension.outputs.file }}
```

**Comment by mcecode** [comment]
I updated the `precommit.yml` workflow to specify the Node.js version to use since what broke the workflow is `vsce` expecting Node.js version 20 or higher. I think specifying the version is a good idea in general since `actions/setup-node` [recommends this](https://github.com/actions/setup-node#usage):

> The `node-version` input is optional. If not supplied, the node version from PATH will be used. However, it is recommended to always specify Node.js version and don't rely on the system one.

Making the version be inline with the [Active LTS](https://nodejs.org/en/about/previous-releases) would also probably be a good idea since this or higher is what libraries usually expect. Maybe we can document this somewhere with a `.node-version` file or something so it's more clear for new contributors what version to use.

**Comment by elijah-potter** [comment]
This looks good to me. There are a couple minor changes I'd like to make, but I can do those after this PR is merged. If you're curious, keep an eye on the commit log.

**Pull request merged**
